name: Production Deployment Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prelive"
        type: choice
        options:
          - prelive
          - live
      version:
        description: "Docker image tag/version to deploy e.g.: v0.0.1"
        required: true
        type: string
      action:
        description: "Action to perform"
        required: true
        default: "run"
        type: choice
        options:
          - run
          - stop
          - restart
          - status

jobs:
  deploy:
    name: Deploy document-service to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Nomad
        uses: dpfisterer/ssh-deploy-to-nomad@v1
        with:
          ssh-host: ${{ vars.DEPLOYMENT_HOST }}
          ssh-user: ${{ vars.DEPLOYMENT_USER }}
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          service-name: document-service
          hcl-template: .github/deployment/nomad/nomad.template.hcl
          hcl-variables: .github/deployment/nomad/nomad.vars.hcl
          action: ${{ github.event.inputs.action }}
          # ⚠️ IMPORTANT: Array values MUST be quoted as strings!
          # Numbers and booleans should NOT be quoted.
          # See VARIABLE_SUBSTITUTION.md for details.
          env-vars: |
            DATACENTER: '["dc1"]'
            DOCUMENT_SERVICE_IMAGE: ghcr.io/seybold-gmbh/document-service:${{ github.event.inputs.version }}
            DOCUMENT_SERVICE_COUNT: ${{ vars.DOCUMENT_SERVICE_COUNT || 1 }}
            DOCUMENT_SERVICE_HOST: document-service.${{ github.event.inputs.environment }}.${{ vars.DOMAIN }}
            DOCUMENT_SERVICE_CPU: ${{ vars.DOCUMENT_SERVICE_CPU || 100 }}
            DOCUMENT_SERVICE_MEMORY: ${{ vars.DOCUMENT_SERVICE_MEMORY || 256 }}
            DOCUMENT_SERVICE_S3_BUCKET: ${{ vars.DOCUMENT_SERVICE_S3_BUCKET || '' }}
            DOCUMENT_SERVICE_S3_PREFIX: ${{ secrets.DOCUMENT_SERVICE_S3_PREFIX || '' }}
            DOCUMENT_SERVICE_S3_ENDPOINT: ${{ vars.DOCUMENT_SERVICE_S3_ENDPOINT || '' }}
            DOCUMENT_SERVICE_S3_REGION: ${{ vars.DOCUMENT_SERVICE_S3_REGION || '' }}
            DOCUMENT_SERVICE_S3_ACCESS_KEY: ${{ secrets.DOCUMENT_SERVICE_S3_ACCESS_KEY || '' }}
            DOCUMENT_SERVICE_S3_SECRET_KEY: ${{ secrets.DOCUMENT_SERVICE_S3_SECRET_KEY || '' }}
            DEPLOY_ENVIRONMENT: ${{ github.event.inputs.environment }}
            DOCUMENT_SERVICE_JWT_SECRET: ${{ secrets.DOCUMENT_SERVICE_JWT_SECRET || '' }}
            DOCUMENT_SERVICE_JWT_OAUTH2_CLIENT_ID: ${{ secrets.DOCUMENT_SERVICE_JWT_OAUTH2_CLIENT_ID || '' }}
            DOCUMENT_SERVICE_JWT_TENANT_ID: ${{ secrets.DOCUMENT_SERVICE_JWT_TENANT_ID || '' }}
