name: Production Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prelive"
        type: choice
        options:
          - prelive
          - live
      version:
        description: "Docker image tag/version to deploy e.g.: v0.0.1"
        required: true
        default: ""
        type: string
      action:
        description: "Action to perform"
        required: true
        default: "run"
        type: choice
        options:
          - run
          - stop
          - restart
          - status

jobs:
  deploy:
    name: Deploy document-service to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Deploy to Nomad
        uses: dpfisterer/ssh-deploy-to-nomad@v1.1.0
        with:
          ssh-host: ${{ vars.DEPLOYMENT_HOST }}
          ssh-user: ${{ vars.DEPLOYMENT_USER }}
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          service-name: document-service-${{ github.event.inputs.environment }}
          hcl-template: .github/deployment/nomad/nomad.template.hcl
          hcl-variables: .github/deployment/nomad/nomad.vars.hcl
          action: ${{ github.event.inputs.action }}
          # ⚠️ WICHTIG: Arrays müssen als String in Single-Quotes stehen!
          env-vars: |
            DATACENTER: '["dc1"]'
            DEPLOY_ENVIRONMENT: ${{ github.event.inputs.environment }}
            DOCUMENT_SERVICE_COUNT: ${{ vars.COUNT || 1 }}
            DOCUMENT_SERVICE_CPU: ${{ vars.DOCUMENT_SERVICE_CPU || 100 }}
            DOCUMENT_SERVICE_HOST: document-service.${{ github.event.inputs.environment }}.${{ vars.DOMAIN }}
            DOCUMENT_SERVICE_IMAGE: ghcr.io/seybold-gmbh/document-service:${{ github.event.inputs.version }}
            DOCUMENT_SERVICE_JWT_OAUTH2_CLIENT_ID: ${{ secrets.DOCUMENT_SERVICE_JWT_OAUTH2_CLIENT_ID }}
            DOCUMENT_SERVICE_JWT_SECRET: ${{ secrets.JWT_SECRET }}
            DOCUMENT_SERVICE_JWT_TENANT_ID: ${{ secrets.DOCUMENT_SERVICE_JWT_TENANT_ID }}
            DOCUMENT_SERVICE_MEMORY: ${{ vars.DOCUMENT_SERVICE_MEMORY || 256 }}
            DOCUMENT_SERVICE_S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
            DOCUMENT_SERVICE_S3_BUCKET: ${{ vars.DOCUMENTS_S3_BUCKET }}
            DOCUMENT_SERVICE_S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
            DOCUMENT_SERVICE_S3_PREFIX: ${{ secrets.DOCUMENT_SERVICE_S3_PREFIX || '' }}
            DOCUMENT_SERVICE_S3_REGION: ${{ vars.S3_REGION }}
            DOCUMENT_SERVICE_S3_SECRET_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
